version: '3'

services:
  mongo:
    image: mongo:6.0.4
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: catalog
      MONGO_INITDB_ROOT_PASSWORD: catalog
      MONGO_INITDB_DATABASE: admin
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"